# -*- coding: utf-8 -*-
"""
Created on Sat Feb  3 12:36:12 2018

@author: Rajesh Rajendran
@Purpose - for the assignement
"""

'''
Assignment 4
'''

import networkx as nx
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
#from sklearn.naive_bayes import GaussianNB
#from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
#from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score        
#from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing

'''
Part 1 - Random Graph Identification
For the first part of this assignment you will analyze randomly generated graphs and determine which algorithm created them.
'''

P1_Graphs = pickle.load(open('A4_graphs','rb'))

'''
P1_Graphs is a list containing 5 networkx graphs. Each of these graphs were generated by one of three possible algorithms:

Preferential Attachment ('PA')
Small World with low probability of rewiring ('SW_L')
Small World with high probability of rewiring ('SW_H')
Anaylze each of the 5 graphs and determine which of the three algorithms generated the graph.

The graph_identification function should return a list of length 5 where each element in the list is either 'PA', 'SW_L', or 'SW_H'.
'''

def graph_identification():
    b = []
    for g in range(0, len(P1_Graphs)):
        deg = np.max(list(P1_Graphs[g].degree().values()))
        clus = nx.average_clustering(P1_Graphs[g])
        
        if deg > 80 :
            a = 'PA'
        elif clus >= 0.1:
            a = 'SW_L'
        else:
            a = 'SW_H'
        
        b.append(a)
    return b

graph_identification()

'''
Part 2 - Company Emails
For the second part of this assignment you will be workking with a company's email network where each node corresponds to a person at the company, and each edge indicates that at least one email has been sent between two people.

The network also contains the node attributes Department and ManagementSalary.

Department indicates the department in the company which the person belongs to, and ManagementSalary indicates whether that person is receiving a management position salary.
'''

G = nx.read_gpickle('email_prediction.txt')
​
print(nx.info(G))

'''
Part 2A - Salary Prediction
Using network G, identify the people in the network with missing values for the node attribute ManagementSalary and predict whether or not these individuals are receiving a management position salary.

To accomplish this, you will need to create a matrix of node features using networkx, train a sklearn classifier on nodes that have ManagementSalary data, and predict a probability of the node receiving a management salary for nodes where ManagementSalary is missing.

Your predictions will need to be given as the probability that the corresponding employee is receiving a management position salary.

The evaluation metric for this assignment is the Area Under the ROC Curve (AUC).

Your grade will be based on the AUC score computed for your classifier. A model which with an AUC of 0.88 or higher will receive full points, and with an AUC of 0.82 or higher will pass (get 80% of the full points).

Using your trained classifier, return a series of length 252 with the data being the probability of receiving management salary, and the index being the node id.

Example:

    1       1.0
    2       0.0
    5       0.8
    8       1.0
        ...
    996     0.7
    1000    0.5
    1001    0.0
    Length: 252, dtype: float64
'''

def salary_predictions():
    features = ['Degree', 'Clusters','DegreeCentrality', 'ClosenessCentrality', 'BetweennessCentrality']
    #features = ['HubScore', 'Authority']
    df = pd.DataFrame(index = G.nodes())

    hit = nx.hits(G)
    #df['HubScore'] = hit[0].values()
    #df['Authority'] = hit[1].values()
    df['Degree'] = pd.Series(nx.degree(G))
    df['Clusters'] = pd.Series(nx.clustering(G))
    df['DegreeCentrality'] = pd.Series(nx.degree_centrality(G))
    df['ClosenessCentrality'] = pd.Series(nx.closeness_centrality(G))
    df['BetweennessCentrality'] = pd.Series(nx.betweenness_centrality(G))
    df['Department'] = pd.Series(nx.get_node_attributes(G, 'Department'))
    df['ManagementSalary'] = pd.Series(nx.get_node_attributes(G, 'ManagementSalary'))
    
    dfpredict = df[np.isnan(df['ManagementSalary']) == True]
    dfknown = df[np.isnan(df['ManagementSalary']) == False]
    dfdata = dfknown[features]
    scaler = StandardScaler().fit(dfdata)
    dfdata = scaler.transform(dfdata)
    dflabels = np.array(dfknown['ManagementSalary'])
    train_features, test_features, train_labels, test_labels = train_test_split(dfdata,dflabels, test_size=0.25)
    
    pln = LogisticRegression()
    model = pln.fit(train_features, train_labels)
    #prediction_probability = pln.predict_proba(test_features)[:,1]
    #preds = pln.predict(test_features)
    #roc_auc_score(test_labels,preds)
    
    dfdata = dfpredict[features]
    dfdata = scaler.transform(dfdata)
    #dflabels = np.array(dfpredict['ManagementSalary'])
    prediction_probability = pln.predict_proba(dfdata)[:,1]
    preds = pln.predict(dfdata)
    
    #p = scaler.transform (np.array(dfpredict[[features]]))
    #preds = pln.predict(p)
    #prediction_probability = pln.predict_proba(p)[:,1]

    #fpr, tpr, _ = roc_curve(test_labels, pln.decision_function(test_features))
    #roc_auc = auc(fpr, tpr)

    return pd.Series([p for p in prediction_probability], index=dfpredict.index.values)

'''
Part 2B - New Connections Prediction
For the last part of this assignment, you will predict future connections between employees of the network. The future connections information has been loaded into the variable future_connections. The index is a tuple indicating a pair of nodes that currently do not have a connection, and the Future Connection column indicates if an edge between those two nodes will exist in the future, where a value of 1.0 indicates a future connection.
'''

future_connections = pd.read_csv('Future_Connections.csv', index_col=0, converters={0: eval})
future_connections.head(10)

'''
Future Connection
(6, 840)	0.0
(4, 197)	0.0
(620, 979)	0.0
(519, 872)	0.0
(382, 423)	0.0
Using network G and future_connections, identify the edges in future_connections with missing values and predict whether or not these edges will have a future connection.

To accomplish this, you will need to create a matrix of features for the edges found in future_connections using networkx, train a sklearn classifier on those edges in future_connections that have Future Connection data, and predict a probability of the edge being a future connection for those edges in future_connections where Future Connection is missing.

Your predictions will need to be given as the probability of the corresponding edge being a future connection.

The evaluation metric for this assignment is the Area Under the ROC Curve (AUC).

Your grade will be based on the AUC score computed for your classifier. A model which with an AUC of 0.88 or higher will receive full points, and with an AUC of 0.82 or higher will pass (get 80% of the full points).

Using your trained classifier, return a series of length 122112 with the data being the probability of the edge being a future connection, and the index being the edge as represented by a tuple of nodes.

Example:

    (107, 348)    0.35
    (542, 751)    0.40
    (20, 426)     0.55
    (50, 989)     0.35
              ...
    (939, 940)    0.15
    (555, 905)    0.35
    (75, 101)     0.65
    Length: 122112, dtype: float64

'''
#Feature Selection Models 1) resource allocation 2) jaccard coefficient 3) preferential attachment 4) adamic adar index
fv = pd.DataFrame()
fv['ra'] = list(nx.resource_allocation_index(G))
fv['jc'] = list(nx.jaccard_coefficient(G))
fv['pa'] = list(nx.preferential_attachment(G))
fv['aa'] = list(nx.adamic_adar_index(G))

adjust_tuples = lambda t : (t[0], t[1])
get_tuples = lambda t : t[2]

fv['tup'] = fv['ra'].apply(adjust_tuples)
fv['ra'] = fv['ra'].apply(get_tuples)
fv['jc'] = fv['jc'].apply(get_tuples)
fv['pa'] = fv['pa'].apply(get_tuples)
fv['aa'] = fv['aa'].apply(get_tuples)
fv.index = fv['tup']
fv = fv.sort_values(by=['tup'])

future_connections = future_connections.reset_index()
future_connections.index = future_connections['index']
future_connections = future_connections.sort_values(by=['index'])
future_connections['ra'] = fv['ra']
future_connections['jc'] = fv['jc']
future_connections['pa'] = fv['pa']
future_connections['aa'] = fv['aa']

def new_connections_predictions():
    features = ['ra', 'jc','pa', 'aa']
    df = future_connections
    dfpredict = df[np.isnan(df['Future Connection']) == True]
    dfknown = df[np.isnan(df['Future Connection']) == False]
    dfdata = dfknown[features]
    scaler = StandardScaler().fit(dfdata)
    dfdata = scaler.transform(dfdata)
    dflabels = np.array(dfknown['Future Connection'])
    train_features, test_features, train_labels, test_labels = train_test_split(dfdata,dflabels, test_size=0.25)
    pln = LogisticRegression()
    model = pln.fit(train_features, train_labels)
    dfdata = dfpredict[features]
    dfdata = scaler.transform(dfdata)
    #dflabels = np.array(dfpredict['ManagementSalary'])
    prediction_probability = pln.predict_proba(dfdata)[:,1]
    preds = pln.predict(dfdata)
    return pd.Series([p for p in prediction_probability], index=dfpredict.index.values)

#Post 1:
#https://www.coursera.org/learn/python-social-network-analysis/discussions/all/threads/_w__VtEbEeeT2RIs_W-FMg/replies/-MAjtNGAEeexuwrR6wbv6A/comments/gVcX-9hjEeeerg6JA-5x3A
#Post 2 (which also as a reference to Post 1):
#https://www.coursera.org/learn/python-social-network-analysis/discussions/all/threads/OpGTxqxmEeeB2hJL-yunuA/replies/VszoUayAEee7eQoPPhIfbA/comments/NXIQithqEeex6A7lu81O-A
    

#writer = pd.ExcelWriter('df.xlsx')
#future_connections.to_excel(writer, sheet_name='Sheet1')
#fv.to_excel(writer, sheet_name='Sheet2')
#writer.save()